NO_COMPANIES_TABLE = "no_companies"
NO_WEBSITES_TABLE = "no_websites"
NO_INDUSTRIES_TABLE = "no_industries"
NO_FINANCIAL_STATEMENTS_TABLE = "no_financial_statements"

NORWAY_RESOLVED_TABLES = (
    NO_COMPANIES_TABLE,
    NO_WEBSITES_TABLE,
    NO_INDUSTRIES_TABLE,
    NO_FINANCIAL_STATEMENTS_TABLE,
)

# source_payload_hash is a per-row SHA256 that cannot compress and nothing
# queries; keep it in DuckDB/dbt staging but drop it from the ClickHouse export.
# See dagster_v3/CLAUDE.md. RESOLVED_TABLE_COLUMNS stays the full migration
# contract; RESOLVED_EXPORT_COLUMNS drives the ClickHouse insert.
CLICKHOUSE_EXCLUDED_COLUMNS = frozenset({"source_payload_hash"})

RESOLVED_TABLE_COLUMNS = {
    NO_COMPANIES_TABLE: (
        "org_number",
        "country_iso2",
        "name",
        "name_normalized",
        "registration_date",
        "incorporation_date",
        "lifecycle_status",
        "is_active",
        "legal_form_code",
        "legal_form_description_original",
        "legal_form_description_language",
        "legal_form_description_en",
        "legal_form_description_translated_at",
        "legal_form_description_translation_provider",
        "legal_form_description_translation_model",
        "company_description_original",
        "articles_purpose_original",
        "activity_text_original",
        "primary_website_url",
        "primary_website_host",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "resolved_at",
    ),
    NO_WEBSITES_TABLE: (
        "org_number",
        "website_url",
        "website_normalized_url",
        "website_host",
        "root_domain",
        "website_path",
        "registered_on",
        "ended_on",
        "is_current",
        "is_primary",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "resolved_at",
    ),
    NO_INDUSTRIES_TABLE: (
        "org_number",
        "source_industry_code",
        "source_industry_code_set",
        "description_original",
        "description_language",
        "description_en",
        "description_translated_at",
        "description_translation_provider",
        "description_translation_model",
        "nace_revision",
        "nace_code",
        "nace_normalized_code",
        "nace_mapping_method",
        "nace_mapping_status",
        "is_primary",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "resolved_at",
    ),
    NO_FINANCIAL_STATEMENTS_TABLE: (
        "country_iso2",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "org_number",
        "legal_name",
        "last_submitted_accounts_year",
        "filing_id",
        "journal_number",
        "accounts_type",
        "legal_form_code",
        "is_parent_company",
        "period_start_date",
        "period_end_date",
        "fiscal_year",
        "currency",
        "liquidation_accounts",
        "statement_layout",
        "is_not_audited",
        "opted_out_audit",
        "is_small_enterprise",
        "accounting_rules",
        "operating_revenue_amount_original",
        "operating_revenue_amount_usd",
        "operating_costs_amount_original",
        "operating_costs_amount_usd",
        "operating_result_amount_original",
        "operating_result_amount_usd",
        "net_financial_items_amount_original",
        "net_financial_items_amount_usd",
        "pretax_result_amount_original",
        "pretax_result_amount_usd",
        "net_result_amount_original",
        "net_result_amount_usd",
        "total_assets_amount_original",
        "total_assets_amount_usd",
        "current_assets_amount_original",
        "current_assets_amount_usd",
        "fixed_assets_amount_original",
        "fixed_assets_amount_usd",
        "equity_amount_original",
        "equity_amount_usd",
        "total_debt_amount_original",
        "total_debt_amount_usd",
        "current_liabilities_amount_original",
        "current_liabilities_amount_usd",
        "long_term_liabilities_amount_original",
        "long_term_liabilities_amount_usd",
        "fx_rate_to_usd",
        "fx_rate_date",
        "fx_source",
        "source_url",
        "resolved_at",
    ),
}

RESOLVED_EXPORT_COLUMNS = {
    table: tuple(
        column for column in columns if column not in CLICKHOUSE_EXCLUDED_COLUMNS
    )
    for table, columns in RESOLVED_TABLE_COLUMNS.items()
}
