/** EU-27 plus the three EEA EFTA states, for the procurement country filter.
 * EEA is included because TED carries Norwegian notices; a strict EU list
 * would grey out a country that has data. Sorted by English name. */
export const EU_EEA_COUNTRIES: { iso2: string; name: string }[] = [
  { iso2: "AT", name: "Austria" },
  { iso2: "BE", name: "Belgium" },
  { iso2: "BG", name: "Bulgaria" },
  { iso2: "HR", name: "Croatia" },
  { iso2: "CY", name: "Cyprus" },
  { iso2: "CZ", name: "Czechia" },
  { iso2: "DK", name: "Denmark" },
  { iso2: "EE", name: "Estonia" },
  { iso2: "FI", name: "Finland" },
  { iso2: "FR", name: "France" },
  { iso2: "DE", name: "Germany" },
  { iso2: "GR", name: "Greece" },
  { iso2: "HU", name: "Hungary" },
  { iso2: "IS", name: "Iceland" },
  { iso2: "IE", name: "Ireland" },
  { iso2: "IT", name: "Italy" },
  { iso2: "LV", name: "Latvia" },
  { iso2: "LI", name: "Liechtenstein" },
  { iso2: "LT", name: "Lithuania" },
  { iso2: "LU", name: "Luxembourg" },
  { iso2: "MT", name: "Malta" },
  { iso2: "NL", name: "Netherlands" },
  { iso2: "NO", name: "Norway" },
  { iso2: "PL", name: "Poland" },
  { iso2: "PT", name: "Portugal" },
  { iso2: "RO", name: "Romania" },
  { iso2: "SK", name: "Slovakia" },
  { iso2: "SI", name: "Slovenia" },
  { iso2: "ES", name: "Spain" },
  { iso2: "SE", name: "Sweden" },
];
