"""Table contracts for Finland PRH XBRL outputs."""

import polars as pl

STATEMENT_DOCUMENTS_TABLE = "fi_prh_xbrl_statement_documents"
FACTS_TABLE = "fi_prh_xbrl_facts_raw"

STATEMENT_DOCUMENTS_POLARS_SCHEMA = {
    "statement_key": pl.Utf8,
    "source_run_id": pl.Utf8,
    "business_id": pl.Utf8,
    "financial_date": pl.Utf8,
    "registration_date": pl.Utf8,
    "source_url": pl.Utf8,
    "xml_object_key": pl.Utf8,
    "xml_sha256": pl.Utf8,
    "xml_size_bytes": pl.Int64,
    "root_name": pl.Utf8,
    "schema_refs": pl.Utf8,
    "taxonomy_entrypoint": pl.Utf8,
    "reported_business_id": pl.Utf8,
    "reported_company_name": pl.Utf8,
    "reported_period_start": pl.Utf8,
    "reported_period_end": pl.Utf8,
    "contexts_count": pl.Int64,
    "units_count": pl.Int64,
    "facts_count": pl.Int64,
    "validation_warnings": pl.Utf8,
    "parser_version": pl.Utf8,
    "parsed_at": pl.Utf8,
}
STATEMENT_DOCUMENTS_COLUMNS = list(STATEMENT_DOCUMENTS_POLARS_SCHEMA)

FACTS_POLARS_SCHEMA = {
    "statement_key": pl.Utf8,
    "business_id": pl.Utf8,
    "financial_date": pl.Utf8,
    "fact_ordinal": pl.Int64,
    "concept_qname": pl.Utf8,
    "concept_namespace": pl.Utf8,
    "concept_local_name": pl.Utf8,
    "context_id": pl.Utf8,
    "unit_id": pl.Utf8,
    "decimals": pl.Utf8,
    "precision": pl.Utf8,
    "value_kind": pl.Utf8,
    "raw_value": pl.Utf8,
    "numeric_value": pl.Utf8,
    "date_value": pl.Utf8,
    "text_value": pl.Utf8,
    "mcy_member_code": pl.Utf8,
    "mcy_member_label_fi": pl.Utf8,
    "ref_member_code": pl.Utf8,
    "ref_member_label_fi": pl.Utf8,
    "is_comparative": pl.Boolean,
    "dimensions": pl.Utf8,
    "parser_version": pl.Utf8,
    "parsed_at": pl.Utf8,
}
FACTS_COLUMNS = list(FACTS_POLARS_SCHEMA)

FINANCIAL_METRICS_COLUMNS = [
    "statement_key",
    "business_id",
    "financial_date",
    "registration_date",
    "period_start",
    "period_end",
    "reported_company_name",
    "source_url",
    "xml_object_key",
    "xml_sha256",
    "xml_size_bytes",
    "source_run_id",
    "revenue",
    "operating_profit_loss",
    "profit_loss",
    "total_assets",
    "equity",
    "liabilities",
    "cash_and_bank",
    "current_assets",
    "current_receivables",
    "current_liabilities",
    "personnel_expenses",
    "wages_and_salaries",
    "employees",
    "source_fact_count",
    "mapped_fact_count",
    "unmapped_numeric_fact_count",
    "metric_warnings",
    "mapping_version",
    "built_at",
]
FINANCIAL_METRICS_POLARS_SCHEMA = {
    "statement_key": pl.Utf8,
    "business_id": pl.Utf8,
    "financial_date": pl.Utf8,
    "registration_date": pl.Utf8,
    "period_start": pl.Utf8,
    "period_end": pl.Utf8,
    "reported_company_name": pl.Utf8,
    "source_url": pl.Utf8,
    "xml_object_key": pl.Utf8,
    "xml_sha256": pl.Utf8,
    "xml_size_bytes": pl.Int64,
    "source_run_id": pl.Utf8,
    "revenue": pl.Float64,
    "operating_profit_loss": pl.Float64,
    "profit_loss": pl.Float64,
    "total_assets": pl.Float64,
    "equity": pl.Float64,
    "liabilities": pl.Float64,
    "cash_and_bank": pl.Float64,
    "current_assets": pl.Float64,
    "current_receivables": pl.Float64,
    "current_liabilities": pl.Float64,
    "personnel_expenses": pl.Float64,
    "wages_and_salaries": pl.Float64,
    "employees": pl.Int64,
    "source_fact_count": pl.Int64,
    "mapped_fact_count": pl.Int64,
    "unmapped_numeric_fact_count": pl.Int64,
    "metric_warnings": pl.Utf8,
    "mapping_version": pl.Utf8,
    "built_at": pl.Utf8,
}

FINANCIAL_METRICS_USD_COLUMNS = [
    "statement_key",
    "business_id",
    "financial_date",
    "registration_date",
    "period_start",
    "period_end",
    "reported_company_name",
    "source_url",
    "xml_object_key",
    "xml_sha256",
    "xml_size_bytes",
    "currency_original",
    "revenue_amount_original",
    "revenue_amount_usd",
    "operating_profit_loss_amount_original",
    "operating_profit_loss_amount_usd",
    "profit_loss_amount_original",
    "profit_loss_amount_usd",
    "total_assets_amount_original",
    "total_assets_amount_usd",
    "equity_amount_original",
    "equity_amount_usd",
    "liabilities_amount_original",
    "liabilities_amount_usd",
    "cash_and_bank_amount_original",
    "cash_and_bank_amount_usd",
    "current_assets_amount_original",
    "current_assets_amount_usd",
    "current_receivables_amount_original",
    "current_receivables_amount_usd",
    "current_liabilities_amount_original",
    "current_liabilities_amount_usd",
    "personnel_expenses_amount_original",
    "personnel_expenses_amount_usd",
    "wages_and_salaries_amount_original",
    "wages_and_salaries_amount_usd",
    "employees",
    "source_fact_count",
    "mapped_fact_count",
    "unmapped_numeric_fact_count",
    "metric_warnings",
    "mapping_version",
    "fx_rate_to_usd",
    "fx_rate_date",
    "fx_converted_at",
    "source_system",
    "source_run_id",
    "source_record_id",
    "source_payload_hash",
    "resolved_at",
]
FINANCIAL_METRICS_USD_POLARS_SCHEMA = {
    "statement_key": pl.Utf8,
    "business_id": pl.Utf8,
    "financial_date": pl.Utf8,
    "registration_date": pl.Utf8,
    "period_start": pl.Utf8,
    "period_end": pl.Utf8,
    "reported_company_name": pl.Utf8,
    "source_url": pl.Utf8,
    "xml_object_key": pl.Utf8,
    "xml_sha256": pl.Utf8,
    "xml_size_bytes": pl.Int64,
    "currency_original": pl.Utf8,
    "revenue_amount_original": pl.Float64,
    "revenue_amount_usd": pl.Float64,
    "operating_profit_loss_amount_original": pl.Float64,
    "operating_profit_loss_amount_usd": pl.Float64,
    "profit_loss_amount_original": pl.Float64,
    "profit_loss_amount_usd": pl.Float64,
    "total_assets_amount_original": pl.Float64,
    "total_assets_amount_usd": pl.Float64,
    "equity_amount_original": pl.Float64,
    "equity_amount_usd": pl.Float64,
    "liabilities_amount_original": pl.Float64,
    "liabilities_amount_usd": pl.Float64,
    "cash_and_bank_amount_original": pl.Float64,
    "cash_and_bank_amount_usd": pl.Float64,
    "current_assets_amount_original": pl.Float64,
    "current_assets_amount_usd": pl.Float64,
    "current_receivables_amount_original": pl.Float64,
    "current_receivables_amount_usd": pl.Float64,
    "current_liabilities_amount_original": pl.Float64,
    "current_liabilities_amount_usd": pl.Float64,
    "personnel_expenses_amount_original": pl.Float64,
    "personnel_expenses_amount_usd": pl.Float64,
    "wages_and_salaries_amount_original": pl.Float64,
    "wages_and_salaries_amount_usd": pl.Float64,
    "employees": pl.Int64,
    "source_fact_count": pl.Int64,
    "mapped_fact_count": pl.Int64,
    "unmapped_numeric_fact_count": pl.Int64,
    "metric_warnings": pl.Utf8,
    "mapping_version": pl.Utf8,
    "fx_rate_to_usd": pl.Float64,
    "fx_rate_date": pl.Utf8,
    "fx_converted_at": pl.Utf8,
    "source_system": pl.Utf8,
    "source_run_id": pl.Utf8,
    "source_record_id": pl.Utf8,
    "source_payload_hash": pl.Utf8,
    "resolved_at": pl.Utf8,
}
