FROM node:24-bookworm-slim

RUN npm install -g pnpm@9
COPY package.json pnpm-lock.yaml /app/
WORKDIR /app
RUN pnpm install --frozen-lockfile --prod

COPY app /app/app
COPY tsconfig.json /app/tsconfig.json
COPY content /app/content

CMD ["./node_modules/.bin/tsx", "app/temporal/sweden-people-worker.ts"]
