"""ClickHouse table metadata for Finland PRH YTJ imports."""

IDENTIFIERS_TABLE = "fi_prhytj_identifiers"
STATUSES_TABLE = "fi_prhytj_statuses"
NAMES_TABLE = "fi_prhytj_names"
BUSINESS_LINES_TABLE = "fi_prhytj_business_lines"
BUSINESS_LINE_DESCRIPTIONS_TABLE = "fi_prhytj_business_line_descriptions"
WEBSITES_TABLE = "fi_prhytj_websites"
COMPANY_FORMS_TABLE = "fi_prhytj_company_forms"
COMPANY_FORM_DESCRIPTIONS_TABLE = "fi_prhytj_company_form_descriptions"
COMPANY_SITUATIONS_TABLE = "fi_prhytj_company_situations"
COMPANY_SITUATION_DESCRIPTIONS_TABLE = "fi_prhytj_company_situation_descriptions"
REGISTERED_ENTRIES_TABLE = "fi_prhytj_registered_entries"
REGISTERED_ENTRY_DESCRIPTIONS_TABLE = "fi_prhytj_registered_entry_descriptions"
ADDRESSES_TABLE = "fi_prhytj_addresses"
ADDRESS_POST_OFFICES_TABLE = "fi_prhytj_address_post_offices"
CODE_LIST_TABLE = "fi_prhytj_code_lists"

IDENTIFIER_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "source_position",
    "identifier_scope",
    "identifier_type",
    "identifier_value",
    "registered_on",
    "ended_on",
    "source",
    "is_primary_business_id",
    "ingested_at",
    "source_export_id",
]
STATUS_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "trade_register_status",
    "status",
    "registration_date",
    "end_date",
    "last_modified",
    "lifecycle_status",
    "is_active",
    "ingested_at",
    "source_export_id",
]
NAME_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "source_position",
    "name",
    "name_type_code",
    "version",
    "registered_on",
    "ended_on",
    "is_current",
    "is_primary",
    "ingested_at",
    "source_export_id",
]
BUSINESS_LINE_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "business_line_type",
    "business_line_code_set",
    "registered_on",
    "source",
    "is_primary",
    "ingested_at",
    "source_export_id",
]
BUSINESS_LINE_DESCRIPTION_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "business_line_item_hash",
    "source_position",
    "language_code",
    "description",
    "ingested_at",
    "source_export_id",
]
WEBSITE_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "url",
    "normalized_url",
    "host",
    "path",
    "registered_on",
    "ended_on",
    "is_current",
    "is_primary",
    "ingested_at",
    "source_export_id",
]
COMPANY_FORM_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "source_position",
    "form_type_code",
    "version",
    "registered_on",
    "ended_on",
    "source",
    "is_current",
    "ingested_at",
    "source_export_id",
]
COMPANY_FORM_DESCRIPTION_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "company_form_item_hash",
    "source_position",
    "language_code",
    "description",
    "ingested_at",
    "source_export_id",
]
COMPANY_SITUATION_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "source_position",
    "situation_type_code",
    "registered_on",
    "ended_on",
    "is_current",
    "ingested_at",
    "source_export_id",
]
COMPANY_SITUATION_DESCRIPTION_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "company_situation_item_hash",
    "source_position",
    "language_code",
    "description",
    "ingested_at",
    "source_export_id",
]
REGISTERED_ENTRY_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "source_position",
    "entry_type_code",
    "register_code",
    "authority",
    "registered_on",
    "ended_on",
    "is_current",
    "ingested_at",
    "source_export_id",
]
REGISTERED_ENTRY_DESCRIPTION_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "registered_entry_item_hash",
    "source_position",
    "language_code",
    "description",
    "ingested_at",
    "source_export_id",
]
ADDRESS_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "source_position",
    "address_type_code",
    "street",
    "post_code",
    "building_number",
    "entrance",
    "apartment_number",
    "post_office_box",
    "co",
    "country",
    "registered_on",
    "source",
    "ingested_at",
    "source_export_id",
]
ADDRESS_POST_OFFICE_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_record_id",
    "business_id",
    "source_line_number",
    "source_payload_hash",
    "source_item_hash",
    "address_item_hash",
    "source_position",
    "language_code",
    "city",
    "municipality_code",
    "ingested_at",
    "source_export_id",
]
CODE_LIST_COLUMNS = [
    "country_iso2",
    "source_slug",
    "source_run_id",
    "file_run_id",
    "file_key",
    "code_list",
    "language_code",
    "code",
    "description",
    "source_line_number",
    "source_payload_hash",
    "ingested_at",
    "source_export_id",
]

NORMALIZED_TABLE_COLUMNS = {
    IDENTIFIERS_TABLE: IDENTIFIER_COLUMNS,
    STATUSES_TABLE: STATUS_COLUMNS,
    NAMES_TABLE: NAME_COLUMNS,
    BUSINESS_LINES_TABLE: BUSINESS_LINE_COLUMNS,
    BUSINESS_LINE_DESCRIPTIONS_TABLE: BUSINESS_LINE_DESCRIPTION_COLUMNS,
    WEBSITES_TABLE: WEBSITE_COLUMNS,
    COMPANY_FORMS_TABLE: COMPANY_FORM_COLUMNS,
    COMPANY_FORM_DESCRIPTIONS_TABLE: COMPANY_FORM_DESCRIPTION_COLUMNS,
    COMPANY_SITUATIONS_TABLE: COMPANY_SITUATION_COLUMNS,
    COMPANY_SITUATION_DESCRIPTIONS_TABLE: COMPANY_SITUATION_DESCRIPTION_COLUMNS,
    REGISTERED_ENTRIES_TABLE: REGISTERED_ENTRY_COLUMNS,
    REGISTERED_ENTRY_DESCRIPTIONS_TABLE: REGISTERED_ENTRY_DESCRIPTION_COLUMNS,
    ADDRESSES_TABLE: ADDRESS_COLUMNS,
    ADDRESS_POST_OFFICES_TABLE: ADDRESS_POST_OFFICE_COLUMNS,
}
NORMALIZED_TABLES = list(NORMALIZED_TABLE_COLUMNS)
