"""Parquet table contract for parsed Finland PRH XBRL outputs."""

STATEMENT_DOCUMENTS_TABLE = "fi_prh_xbrl_statement_documents"
FACTS_TABLE = "fi_prh_xbrl_facts_raw"
XML_DOCUMENTS_TABLE = "fi_prh_xbrl_xml_documents"
FINANCIAL_METRICS_TABLE = "fi_prh_xbrl_financial_metrics"

TABLE_COLUMNS = {
    XML_DOCUMENTS_TABLE: [
        "business_id",
        "financial_date",
        "registration_date",
        "source_url",
        "xml_object_key",
        "xml_sha256",
        "xml_size_bytes",
        "downloaded",
        "reused",
        "discovery_registered_date_start",
        "discovery_registered_date_end",
        "financial_start_date",
        "max_reports",
        "selected_at",
    ],
    STATEMENT_DOCUMENTS_TABLE: [
        "statement_key",
        "source_run_id",
        "business_id",
        "financial_date",
        "registration_date",
        "source_url",
        "xml_object_key",
        "xml_sha256",
        "xml_size_bytes",
        "root_name",
        "schema_refs",
        "taxonomy_entrypoint",
        "reported_business_id",
        "reported_company_name",
        "reported_period_start",
        "reported_period_end",
        "contexts_count",
        "units_count",
        "facts_count",
        "validation_warnings",
        "parser_version",
        "parsed_at",
    ],
    FACTS_TABLE: [
        "statement_key",
        "business_id",
        "financial_date",
        "fact_ordinal",
        "concept_qname",
        "concept_namespace",
        "concept_local_name",
        "context_id",
        "unit_id",
        "decimals",
        "precision",
        "value_kind",
        "raw_value",
        "numeric_value",
        "date_value",
        "text_value",
        "mcy_member_code",
        "mcy_member_label_fi",
        "ref_member_code",
        "ref_member_label_fi",
        "is_comparative",
        "dimensions",
        "parser_version",
        "parsed_at",
    ],
    FINANCIAL_METRICS_TABLE: [
        "statement_key",
        "business_id",
        "financial_date",
        "period_start",
        "period_end",
        "revenue",
        "operating_profit_loss",
        "profit_loss",
        "total_assets",
        "equity",
        "liabilities",
        "cash_and_bank",
        "current_assets",
        "current_receivables",
        "current_liabilities",
        "personnel_expenses",
        "wages_and_salaries",
        "employees",
        "source_fact_count",
        "mapped_fact_count",
        "unmapped_numeric_fact_count",
        "metric_warnings",
        "mapping_version",
        "built_at",
    ],
}
