EODHD_EXCHANGES_TABLE = "eodhd_exchanges"
EODHD_EXCHANGE_MICS_TABLE = "eodhd_exchange_mics"
EODHD_SYMBOLS_TABLE = "eodhd_symbols"
EODHD_SYMBOL_MICS_TABLE = "eodhd_symbol_mics"
EODHD_EOD_PRICES_TABLE = "eodhd_eod_prices"

EODHD_REFERENCE_TABLES = (
    EODHD_EXCHANGES_TABLE,
    EODHD_EXCHANGE_MICS_TABLE,
    EODHD_SYMBOLS_TABLE,
    EODHD_SYMBOL_MICS_TABLE,
)

EODHD_TABLE_COLUMNS = {
    EODHD_EXCHANGES_TABLE: (
        "exchange_code",
        "exchange_name",
        "country_name",
        "country_iso2",
        "country_iso3",
        "currency",
        "operating_mic_raw",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
    ),
    EODHD_EXCHANGE_MICS_TABLE: (
        "exchange_code",
        "mic",
        "mic_position",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
    ),
    EODHD_SYMBOLS_TABLE: (
        "eodhd_symbol_key",
        "exchange_code",
        "reported_exchange_code",
        "ticker",
        "symbol_name",
        "country_name",
        "currency",
        "instrument_type",
        "isin",
        "is_delisted",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
    ),
    EODHD_SYMBOL_MICS_TABLE: (
        "eodhd_symbol_key",
        "mic",
        "is_primary",
        "resolution_method",
        "resolution_confidence",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "resolved_at",
    ),
    EODHD_EOD_PRICES_TABLE: (
        "eodhd_symbol_key",
        "exchange_code",
        "ticker",
        "price_date",
        "open",
        "high",
        "low",
        "close",
        "adjusted_close",
        "volume",
        "currency",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "source_object_key",
        "retrieved_at",
    ),
}

EODHD_DUCKDB_COLUMN_TYPES = {
    EODHD_EXCHANGES_TABLE: {
        "exchange_code": "VARCHAR",
        "exchange_name": "VARCHAR",
        "country_name": "VARCHAR",
        "country_iso2": "VARCHAR",
        "country_iso3": "VARCHAR",
        "currency": "VARCHAR",
        "operating_mic_raw": "VARCHAR",
        "source_system": "VARCHAR",
        "source_run_id": "VARCHAR",
        "source_record_id": "VARCHAR",
        "source_payload_hash": "VARCHAR",
        "retrieved_at": "TIMESTAMP",
    },
    EODHD_EXCHANGE_MICS_TABLE: {
        "exchange_code": "VARCHAR",
        "mic": "VARCHAR",
        "mic_position": "USMALLINT",
        "source_system": "VARCHAR",
        "source_run_id": "VARCHAR",
        "source_record_id": "VARCHAR",
        "source_payload_hash": "VARCHAR",
        "retrieved_at": "TIMESTAMP",
    },
    EODHD_SYMBOLS_TABLE: {
        "eodhd_symbol_key": "VARCHAR",
        "exchange_code": "VARCHAR",
        "reported_exchange_code": "VARCHAR",
        "ticker": "VARCHAR",
        "symbol_name": "VARCHAR",
        "country_name": "VARCHAR",
        "currency": "VARCHAR",
        "instrument_type": "VARCHAR",
        "isin": "VARCHAR",
        "is_delisted": "UTINYINT",
        "source_system": "VARCHAR",
        "source_run_id": "VARCHAR",
        "source_record_id": "VARCHAR",
        "source_payload_hash": "VARCHAR",
        "retrieved_at": "TIMESTAMP",
    },
    EODHD_SYMBOL_MICS_TABLE: {
        "eodhd_symbol_key": "VARCHAR",
        "mic": "VARCHAR",
        "is_primary": "UTINYINT",
        "resolution_method": "VARCHAR",
        "resolution_confidence": "VARCHAR",
        "source_system": "VARCHAR",
        "source_run_id": "VARCHAR",
        "source_record_id": "VARCHAR",
        "source_payload_hash": "VARCHAR",
        "resolved_at": "TIMESTAMP",
    },
    EODHD_EOD_PRICES_TABLE: {
        "eodhd_symbol_key": "VARCHAR",
        "exchange_code": "VARCHAR",
        "ticker": "VARCHAR",
        "price_date": "DATE",
        "open": "DECIMAL(20, 8)",
        "high": "DECIMAL(20, 8)",
        "low": "DECIMAL(20, 8)",
        "close": "DECIMAL(20, 8)",
        "adjusted_close": "DECIMAL(20, 8)",
        "volume": "UBIGINT",
        "currency": "VARCHAR",
        "source_system": "VARCHAR",
        "source_run_id": "VARCHAR",
        "source_record_id": "VARCHAR",
        "source_payload_hash": "VARCHAR",
        "source_object_key": "VARCHAR",
        "retrieved_at": "TIMESTAMP",
    },
}
