CREATE DATABASE IF NOT EXISTS corpscout;

CREATE TABLE IF NOT EXISTS corpscout.fi_financial_metrics
(
    statement_key String,
    business_id String,
    financial_date Date,
    registration_date Nullable(Date),
    period_start Nullable(Date),
    period_end Nullable(Date),
    reported_company_name Nullable(String),
    source_url Nullable(String),
    xml_object_key Nullable(String),
    xml_sha256 Nullable(FixedString(64)),
    xml_size_bytes Nullable(UInt64),
    currency_original LowCardinality(String),
    revenue_amount_original Nullable(Decimal(38, 6)),
    revenue_amount_usd Nullable(Decimal(38, 6)),
    operating_profit_loss_amount_original Nullable(Decimal(38, 6)),
    operating_profit_loss_amount_usd Nullable(Decimal(38, 6)),
    profit_loss_amount_original Nullable(Decimal(38, 6)),
    profit_loss_amount_usd Nullable(Decimal(38, 6)),
    total_assets_amount_original Nullable(Decimal(38, 6)),
    total_assets_amount_usd Nullable(Decimal(38, 6)),
    equity_amount_original Nullable(Decimal(38, 6)),
    equity_amount_usd Nullable(Decimal(38, 6)),
    liabilities_amount_original Nullable(Decimal(38, 6)),
    liabilities_amount_usd Nullable(Decimal(38, 6)),
    cash_and_bank_amount_original Nullable(Decimal(38, 6)),
    cash_and_bank_amount_usd Nullable(Decimal(38, 6)),
    current_assets_amount_original Nullable(Decimal(38, 6)),
    current_assets_amount_usd Nullable(Decimal(38, 6)),
    current_receivables_amount_original Nullable(Decimal(38, 6)),
    current_receivables_amount_usd Nullable(Decimal(38, 6)),
    current_liabilities_amount_original Nullable(Decimal(38, 6)),
    current_liabilities_amount_usd Nullable(Decimal(38, 6)),
    personnel_expenses_amount_original Nullable(Decimal(38, 6)),
    personnel_expenses_amount_usd Nullable(Decimal(38, 6)),
    wages_and_salaries_amount_original Nullable(Decimal(38, 6)),
    wages_and_salaries_amount_usd Nullable(Decimal(38, 6)),
    employees Nullable(UInt64),
    source_fact_count UInt64,
    mapped_fact_count UInt64,
    unmapped_numeric_fact_count UInt64,
    metric_warnings String,
    mapping_version LowCardinality(String),
    fx_rate_to_usd Nullable(Decimal(38, 12)),
    fx_rate_date Nullable(Date),
    fx_converted_at Nullable(DateTime64(3, 'UTC')),
    source_system LowCardinality(String),
    source_run_id String,
    source_record_id String,
    source_payload_hash FixedString(64),
    resolved_at DateTime64(3, 'UTC')
)
ENGINE = ReplacingMergeTree
ORDER BY (business_id, financial_date, statement_key);
