CREATE DATABASE IF NOT EXISTS corpscout;

CREATE TABLE IF NOT EXISTS corpscout.companies
(
    country_iso2 LowCardinality(String),
    source_slug LowCardinality(String),
    source_run_id String,
    source_line_number UInt64,
    source_record_id String,
    source_payload_hash FixedString(64),
    org_number String,
    vat_id String,
    legal_name String,
    legal_form_code String,
    legal_form_description_original String,
    legal_form_description_en String,
    registration_date String,
    incorporation_date String,
    website String,
    phone String,
    nace1_code String,
    nace1_description_original String,
    nace1_description_en String,
    nace2_code String,
    nace2_description_original String,
    nace2_description_en String,
    nace3_code String,
    nace3_description_original String,
    nace3_description_en String,
    articles_purpose_original String,
    articles_purpose_en String,
    activity_text_original String,
    activity_text_en String,
    company_description_original String,
    company_description_en String,
    employee_count Nullable(Int64),
    has_registered_employee_count UInt8,
    business_address_lines String,
    business_postal_code String,
    business_city String,
    business_municipality String,
    business_municipality_code String,
    business_country_code String,
    is_vat_registered UInt8,
    is_enterprise_register_registered UInt8,
    is_group_member UInt8,
    parent_org_number String,
    last_submitted_accounts_year String,
    status LowCardinality(String),
    is_active UInt8,
    source_url String,
    raw_entity String
)
ENGINE = ReplacingMergeTree
ORDER BY (org_number);
