CREATE DATABASE IF NOT EXISTS corpscout;

CREATE TABLE IF NOT EXISTS corpscout.br_cvm_companies
(
    country_iso2 LowCardinality(String),
    source_slug LowCardinality(String),
    source_run_id String,
    source_record_id String,
    cnpj String,
    cnpj_basico String,
    cvm_code LowCardinality(String),
    legal_name String,
    trade_name String,
    registration_date Nullable(Date32),
    constitution_date Nullable(Date32),
    cancellation_date Nullable(Date32),
    cancellation_reason String,
    registration_status LowCardinality(String),
    registration_status_start_date Nullable(Date32),
    industry_sector String,
    market_type String,
    registration_category LowCardinality(String),
    registration_category_start_date Nullable(Date32),
    issuer_status String,
    issuer_status_start_date Nullable(Date32),
    shareholding_control LowCardinality(String),
    address_type LowCardinality(String),
    street String,
    address_complement String,
    district String,
    municipality String,
    state LowCardinality(String),
    country String,
    postal_code String,
    phone_area_code String,
    phone_number String,
    fax_area_code String,
    fax_number String,
    email String,
    responsible_type String,
    responsible_name String,
    responsible_start_date Nullable(Date32),
    responsible_street String,
    responsible_address_complement String,
    responsible_district String,
    responsible_municipality String,
    responsible_state LowCardinality(String),
    responsible_country String,
    responsible_postal_code String,
    responsible_phone_area_code String,
    responsible_phone_number String,
    responsible_fax_area_code String,
    responsible_fax_number String,
    responsible_email String,
    auditor_cnpj String,
    auditor_name String,
    source_url String,
    source_file_name LowCardinality(String),
    source_row_number UInt64,
    resolved_at DateTime64(3, 'UTC')
)
ENGINE = ReplacingMergeTree(resolved_at)
ORDER BY (cnpj, cvm_code);
