REVOKE INSERT ON corpscout.se_company_person_correction
FROM corpscout_person_correction_writer;

REVOKE INSERT ON corpscout.se_company_person_enrichment_observation
FROM corpscout_person_correction_writer;
