CREATE DATABASE IF NOT EXISTS corpscout;

CREATE TABLE IF NOT EXISTS corpscout.esef_disclosures
(
    disclosure_id              FixedString(64),
    disclosure_kind            LowCardinality(String),
    source_document_id         String,
    source_record_uid          FixedString(64),
    source_fact_id             String,
    source_fact_key            String,
    package_sha256             FixedString(64),
    artifact_schema_version    UInt16,
    lei                        String,
    country_iso2               LowCardinality(String),
    company_id                 String,
    period_end                 String,
    fiscal_year                UInt16,
    concept_qname              String,
    concept_local_name         String,
    language                   LowCardinality(String),
    segment                    LowCardinality(String),
    selection_reason           String,
    report_member              String,
    period_json                String,
    section_type               LowCardinality(String),
    page_id                    String,
    printed_page_number        String,
    anchor_xpath               String,
    anchor_visual_order        UInt32,
    extraction_method          LowCardinality(String),
    text_sha256                FixedString(64),
    parser_name                LowCardinality(String),
    parser_version             String,
    blocks_json                String,
    plain_text                 String,
    original_character_count  UInt64,
    block_count                UInt32,
    table_count                UInt32,
    source_run_id              String,
    extracted_at               String,
    processed_week             Date,
    resolved_at                DateTime64(3) DEFAULT now64(3)
)
ENGINE = MergeTree
PARTITION BY processed_week
ORDER BY (
    processed_week,
    source_document_id,
    disclosure_kind,
    segment,
    source_fact_key,
    disclosure_id
);

INSERT INTO corpscout.esef_disclosures
(
    disclosure_id,
    disclosure_kind,
    source_document_id,
    source_record_uid,
    source_fact_id,
    source_fact_key,
    package_sha256,
    artifact_schema_version,
    lei,
    country_iso2,
    company_id,
    period_end,
    fiscal_year,
    concept_qname,
    concept_local_name,
    language,
    segment,
    selection_reason,
    report_member,
    period_json,
    section_type,
    page_id,
    printed_page_number,
    anchor_xpath,
    anchor_visual_order,
    extraction_method,
    text_sha256,
    parser_name,
    parser_version,
    blocks_json,
    plain_text,
    original_character_count,
    block_count,
    table_count,
    source_run_id,
    extracted_at,
    processed_week,
    resolved_at
)
SELECT
    disclosure_id,
    'tagged_fact',
    source_document_id,
    source_record_uid,
    source_fact_id,
    source_fact_id,
    package_sha256,
    toUInt16(4),
    lei,
    country_iso2,
    company_id,
    period_end,
    fiscal_year,
    concept_qname,
    concept_local_name,
    language,
    '',
    '',
    '',
    '{}',
    '',
    '',
    '',
    '',
    toUInt32(0),
    'tagged_fact',
    lower(hex(SHA256(plain_text))),
    parser_name,
    parser_version,
    blocks_json,
    plain_text,
    toUInt64(lengthUTF8(plain_text)),
    block_count,
    table_count,
    source_run_id,
    extracted_at,
    processed_week,
    resolved_at
FROM corpscout.esef_fact_disclosures;

DROP TABLE corpscout.esef_fact_disclosures;
