CREATE DATABASE IF NOT EXISTS norway_brreg;

CREATE TABLE IF NOT EXISTS norway_brreg.financial_statements
(
    country_iso2 LowCardinality(String),
    source_slug LowCardinality(String),
    source_run_id String,
    source_line_number UInt64,
    source_record_id String,
    source_payload_hash FixedString(64),
    org_number String,
    legal_name String,
    website String,
    last_submitted_accounts_year String,
    filing_id Nullable(Int64),
    journal_number String,
    accounts_type LowCardinality(String),
    legal_form_code String,
    is_parent_company UInt8,
    period_start_date Nullable(Date),
    period_end_date Nullable(Date),
    fiscal_year Nullable(Int64),
    currency LowCardinality(String),
    liquidation_accounts UInt8,
    statement_layout String,
    is_not_audited UInt8,
    opted_out_audit UInt8,
    is_small_enterprise UInt8,
    accounting_rules String,
    operating_revenue_amount_original Nullable(Decimal(38, 6)),
    operating_revenue_amount_usd Nullable(Decimal(38, 6)),
    operating_costs_amount_original Nullable(Decimal(38, 6)),
    operating_costs_amount_usd Nullable(Decimal(38, 6)),
    operating_result_amount_original Nullable(Decimal(38, 6)),
    operating_result_amount_usd Nullable(Decimal(38, 6)),
    net_financial_items_amount_original Nullable(Decimal(38, 6)),
    net_financial_items_amount_usd Nullable(Decimal(38, 6)),
    pretax_result_amount_original Nullable(Decimal(38, 6)),
    pretax_result_amount_usd Nullable(Decimal(38, 6)),
    net_result_amount_original Nullable(Decimal(38, 6)),
    net_result_amount_usd Nullable(Decimal(38, 6)),
    total_assets_amount_original Nullable(Decimal(38, 6)),
    total_assets_amount_usd Nullable(Decimal(38, 6)),
    current_assets_amount_original Nullable(Decimal(38, 6)),
    current_assets_amount_usd Nullable(Decimal(38, 6)),
    fixed_assets_amount_original Nullable(Decimal(38, 6)),
    fixed_assets_amount_usd Nullable(Decimal(38, 6)),
    equity_amount_original Nullable(Decimal(38, 6)),
    equity_amount_usd Nullable(Decimal(38, 6)),
    total_debt_amount_original Nullable(Decimal(38, 6)),
    total_debt_amount_usd Nullable(Decimal(38, 6)),
    current_liabilities_amount_original Nullable(Decimal(38, 6)),
    current_liabilities_amount_usd Nullable(Decimal(38, 6)),
    long_term_liabilities_amount_original Nullable(Decimal(38, 6)),
    long_term_liabilities_amount_usd Nullable(Decimal(38, 6)),
    fx_rate_to_usd Nullable(Decimal(38, 12)),
    fx_rate_date Nullable(Date),
    fx_source String,
    source_url String,
    raw_financial_record String
)
ENGINE = ReplacingMergeTree
ORDER BY (org_number, period_end_date, accounts_type);
