"""Coordinate identity registration with final inventory replacement."""

import re

from corpscout_identity.coordination import DOMAIN_COLUMNS, PAGE_COLUMNS, WEBSITE_COLUMNS


def retain_registered_identities(
    client, *, stage: str, table: str, settings: dict, query_id: str
) -> int:
    """Copy late registrations into a completed stage while holding the shared lock.

    Registration inserts missing identities only. Existing metadata is folded by the
    inventory builder, so copying missing natural keys preserves both without updates.
    Sorted joins bound memory even for the central domain inventory.
    """
    columns, keys = {
        "domains": (DOMAIN_COLUMNS, ("root_domain",)),
        "websites": (WEBSITE_COLUMNS, ("root_domain", "website_origin")),
        "pages": (PAGE_COLUMNS, ("root_domain", "website_origin", "page_url")),
    }[table]
    # The stage is generated by the inventory builder, never supplied by an API user.
    if re.fullmatch(rf"corpscout\.{table}_stage_[a-f0-9]{{32}}", stage) is None:
        raise ValueError("Invalid inventory staging table")
    [(before,)] = client.execute(f"SELECT count() FROM {stage}")
    equality = " AND ".join(f"current.{key}=staged.{key}" for key in keys)
    client.execute(
        f"""INSERT INTO {stage} ({",".join(columns)})
        SELECT {",".join("current." + column for column in columns)}
        FROM corpscout.{table} AS current
        LEFT ANY JOIN (SELECT {",".join(keys)},1 AS present FROM {stage}) AS staged
            ON {equality}
        WHERE isNull(staged.present)""",
        settings={
            **settings,
            "async_insert": 0,
            "join_use_nulls": 1,
            "join_algorithm": "full_sorting_merge",
            # The optimizer's ANTI rewrite is unsupported by the sorted join.
            "query_plan_convert_any_join_to_semi_or_anti_join": 0,
        },
        query_id=query_id,
    )
    [(after,)] = client.execute(f"SELECT count() FROM {stage}")
    return after - before
