WIKIDATA_COMPANIES_TABLE = "wikidata_companies"
WIKIDATA_EXCHANGES_TABLE = "wikidata_exchanges"
WIKIDATA_COMPANY_LISTINGS_TABLE = "wikidata_company_listings"
WIKIDATA_COMPANY_IDENTIFIERS_TABLE = "wikidata_company_identifiers"
WIKIDATA_COMPANY_WEBSITES_TABLE = "wikidata_company_websites"
WIKIDATA_COMPANY_RELATIONSHIPS_TABLE = "wikidata_company_relationships"
WIKIDATA_COMPANY_PEOPLE_TABLE = "wikidata_company_people"
WIKIDATA_PERSONS_TABLE = "wikidata_persons"
WIKIDATA_SEED_EXTRACTION_RUNS_TABLE = "wikidata_seed_extraction_runs"

WIKIDATA_TABLES = (
    WIKIDATA_COMPANIES_TABLE,
    WIKIDATA_EXCHANGES_TABLE,
    WIKIDATA_COMPANY_LISTINGS_TABLE,
    WIKIDATA_COMPANY_IDENTIFIERS_TABLE,
    WIKIDATA_COMPANY_WEBSITES_TABLE,
    WIKIDATA_COMPANY_RELATIONSHIPS_TABLE,
    WIKIDATA_COMPANY_PEOPLE_TABLE,
    WIKIDATA_PERSONS_TABLE,
    WIKIDATA_SEED_EXTRACTION_RUNS_TABLE,
)

WIKIDATA_TABLE_COLUMNS = {
    WIKIDATA_COMPANIES_TABLE: (
        "wikidata_id",
        "wikidata_url",
        "name",
        "name_normalized",
        "company_description",
        "official_name",
        "headquarters_wikidata_id",
        "headquarters_label",
        "headquarters_country_wikidata_id",
        "headquarters_country_label",
        "headquarters_country_iso2",
        "country_resolution_method",
        "country_resolution_confidence",
        "inception_date",
        "legal_form_wikidata_id",
        "legal_form_label",
        "employee_count",
        "employee_count_point_in_time",
        "logo_image",
        "logo_image_url",
        "industry_wikidata_id",
        "industry_label",
        "has_current_listing",
        "listing_count",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_EXCHANGES_TABLE: (
        "exchange_wikidata_id",
        "exchange_name",
        "mic",
        "country_wikidata_id",
        "country_name",
        "country_iso2",
        "listed_company_count",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_COMPANY_LISTINGS_TABLE: (
        "wikidata_id",
        "listing_statement_id",
        "exchange_wikidata_id",
        "exchange_name",
        "ticker",
        "isin",
        "is_current",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_COMPANY_IDENTIFIERS_TABLE: (
        "wikidata_id",
        "identifier_type",
        "wikidata_property_id",
        "identifier_value",
        "identifier_scope",
        "is_primary",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_COMPANY_WEBSITES_TABLE: (
        "wikidata_id",
        "website_url",
        "website_normalized_url",
        "website_host",
        "root_domain",
        "website_path",
        "website_kind",
        "confidence",
        "validation_status",
        "is_primary_candidate",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_COMPANY_RELATIONSHIPS_TABLE: (
        "subject_wikidata_id",
        "object_wikidata_id",
        "relationship_type",
        "wikidata_property_id",
        "relationship_statement_id",
        "object_name",
        "start_date",
        "end_date",
        "is_current",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_COMPANY_PEOPLE_TABLE: (
        "company_wikidata_id",
        "person_wikidata_id",
        "role_property",
        "role_label",
        "start_date",
        "end_date",
        "is_current",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_PERSONS_TABLE: (
        "person_wikidata_id",
        "name",
        "name_normalized",
        "description",
        "birth_year",
        "image_url",
        "wikidata_url",
        "source_system",
        "source_run_id",
        "source_record_id",
        "source_payload_hash",
        "retrieved_at",
        "resolved_at",
    ),
    WIKIDATA_SEED_EXTRACTION_RUNS_TABLE: (
        "source_run_id",
        "query_mode",
        "query_exchange_id",
        "query_hash",
        "row_count",
        "distinct_company_count",
        "distinct_listing_count",
        "companies_with_website_count",
        "companies_with_cik_count",
        "companies_with_lei_count",
        "started_at",
        "completed_at",
        "source_system",
    ),
}
