{{ config(materialized='table') }}

select
  country_iso2,
  source_slug as source_system,
  source_run_id,
  source_record_id,
  source_payload_hash,
  org_number,
  legal_name,
  nullif(last_submitted_accounts_year, '') as last_submitted_accounts_year,
  filing_id,
  nullif(journal_number, '') as journal_number,
  accounts_type,
  nullif(legal_form_code, '') as legal_form_code,
  coalesce(is_parent_company, false) as is_parent_company,
  period_start_date,
  period_end_date,
  fiscal_year,
  currency,
  coalesce(liquidation_accounts, false) as liquidation_accounts,
  nullif(statement_layout, '') as statement_layout,
  coalesce(is_not_audited, false) as is_not_audited,
  coalesce(opted_out_audit, false) as opted_out_audit,
  coalesce(is_small_enterprise, false) as is_small_enterprise,
  nullif(accounting_rules, '') as accounting_rules,
  operating_revenue_amount_original,
  operating_revenue_amount_usd,
  operating_costs_amount_original,
  operating_costs_amount_usd,
  operating_result_amount_original,
  operating_result_amount_usd,
  net_financial_items_amount_original,
  net_financial_items_amount_usd,
  pretax_result_amount_original,
  pretax_result_amount_usd,
  net_result_amount_original,
  net_result_amount_usd,
  total_assets_amount_original,
  total_assets_amount_usd,
  current_assets_amount_original,
  current_assets_amount_usd,
  fixed_assets_amount_original,
  fixed_assets_amount_usd,
  equity_amount_original,
  equity_amount_usd,
  total_debt_amount_original,
  total_debt_amount_usd,
  current_liabilities_amount_original,
  current_liabilities_amount_usd,
  long_term_liabilities_amount_original,
  long_term_liabilities_amount_usd,
  fx_rate_to_usd,
  fx_rate_date,
  nullif(fx_source, '') as fx_source,
  source_url,
  now() as resolved_at
from {{ source('norway_brreg', 'financial_statements') }}
where org_number is not null
  and org_number != ''
