version: 2

sources:
  - name: norway_brreg
    schema: norway_brreg
    tables:
      - name: entities
        meta:
          dagster:
            asset_key: ["norway_brreg_entities_duckdb"]
      - name: financial_statements
        meta:
          dagster:
            asset_key: ["norway_brreg_financial_statements_duckdb"]

models:
  - name: no_companies
    columns:
      - name: org_number
        data_tests:
          - not_null
  - name: no_websites
    columns:
      - name: org_number
        data_tests:
          - not_null
      - name: root_domain
        data_tests:
          - not_null
  - name: no_industries
    columns:
      - name: org_number
        data_tests:
          - not_null
  - name: no_financial_statements
    columns:
      - name: org_number
        data_tests:
          - not_null
