from typing import Any

NORWAY_BRREG_DATABASE = "corpscout"
COMPANIES_TABLE = "companies"
FINANCIAL_STATEMENTS_TABLE = "financial_statements"
QUALIFIED_COMPANIES_TABLE = f"{NORWAY_BRREG_DATABASE}.{COMPANIES_TABLE}"
QUALIFIED_FINANCIAL_STATEMENTS_TABLE = (
    f"{NORWAY_BRREG_DATABASE}.{FINANCIAL_STATEMENTS_TABLE}"
)

BRREG_ENTITIES_COLUMNS: dict[str, dict[str, Any]] = {
    "country_iso2": {"data_type": "text"},
    "source_slug": {"data_type": "text"},
    "source_run_id": {"data_type": "text"},
    "source_line_number": {"data_type": "bigint"},
    "source_record_id": {"data_type": "text"},
    "source_payload_hash": {"data_type": "text"},
    "org_number": {"data_type": "text", "nullable": False},
    "vat_id": {"data_type": "text"},
    "legal_name": {"data_type": "text"},
    "legal_form_code": {"data_type": "text"},
    "legal_form_description_original": {"data_type": "text"},
    "legal_form_description_en": {"data_type": "text"},
    "registration_date": {"data_type": "text"},
    "incorporation_date": {"data_type": "text"},
    "website": {"data_type": "text"},
    "phone": {"data_type": "text"},
    "nace1_code": {"data_type": "text"},
    "nace1_description_original": {"data_type": "text"},
    "nace1_description_en": {"data_type": "text"},
    "nace2_code": {"data_type": "text"},
    "nace2_description_original": {"data_type": "text"},
    "nace2_description_en": {"data_type": "text"},
    "nace3_code": {"data_type": "text"},
    "nace3_description_original": {"data_type": "text"},
    "nace3_description_en": {"data_type": "text"},
    "articles_purpose_original": {"data_type": "text"},
    "articles_purpose_en": {"data_type": "text"},
    "activity_text_original": {"data_type": "text"},
    "activity_text_en": {"data_type": "text"},
    "employee_count": {"data_type": "bigint"},
    "has_registered_employee_count": {"data_type": "bool"},
    "business_address_lines": {"data_type": "text"},
    "business_postal_code": {"data_type": "text"},
    "business_city": {"data_type": "text"},
    "business_municipality": {"data_type": "text"},
    "business_municipality_code": {"data_type": "text"},
    "business_country_code": {"data_type": "text"},
    "is_vat_registered": {"data_type": "bool"},
    "is_enterprise_register_registered": {"data_type": "bool"},
    "is_group_member": {"data_type": "bool"},
    "parent_org_number": {"data_type": "text"},
    "last_submitted_accounts_year": {"data_type": "text"},
    "status": {"data_type": "text"},
    "is_active": {"data_type": "bool"},
    "source_url": {"data_type": "text"},
    "raw_entity": {"data_type": "text"},
}


BRREG_FINANCIAL_STATEMENTS_COLUMNS: dict[str, dict[str, Any]] = {
    "country_iso2": {"data_type": "text"},
    "source_slug": {"data_type": "text"},
    "source_run_id": {"data_type": "text"},
    "source_line_number": {"data_type": "bigint"},
    "source_record_id": {"data_type": "text"},
    "source_payload_hash": {"data_type": "text"},
    "org_number": {"data_type": "text", "nullable": False},
    "legal_name": {"data_type": "text"},
    "website": {"data_type": "text"},
    "last_submitted_accounts_year": {"data_type": "text"},
    "filing_id": {"data_type": "bigint"},
    "journal_number": {"data_type": "text"},
    "accounts_type": {"data_type": "text"},
    "legal_form_code": {"data_type": "text"},
    "is_parent_company": {"data_type": "bool"},
    "period_start_date": {"data_type": "date"},
    "period_end_date": {"data_type": "date"},
    "fiscal_year": {"data_type": "bigint"},
    "currency": {"data_type": "text"},
    "liquidation_accounts": {"data_type": "bool"},
    "statement_layout": {"data_type": "text"},
    "is_not_audited": {"data_type": "bool"},
    "opted_out_audit": {"data_type": "bool"},
    "is_small_enterprise": {"data_type": "bool"},
    "accounting_rules": {"data_type": "text"},
    "operating_revenue_amount_original": {"data_type": "decimal"},
    "operating_revenue_amount_usd": {"data_type": "decimal"},
    "operating_costs_amount_original": {"data_type": "decimal"},
    "operating_costs_amount_usd": {"data_type": "decimal"},
    "operating_result_amount_original": {"data_type": "decimal"},
    "operating_result_amount_usd": {"data_type": "decimal"},
    "net_financial_items_amount_original": {"data_type": "decimal"},
    "net_financial_items_amount_usd": {"data_type": "decimal"},
    "pretax_result_amount_original": {"data_type": "decimal"},
    "pretax_result_amount_usd": {"data_type": "decimal"},
    "net_result_amount_original": {"data_type": "decimal"},
    "net_result_amount_usd": {"data_type": "decimal"},
    "total_assets_amount_original": {"data_type": "decimal"},
    "total_assets_amount_usd": {"data_type": "decimal"},
    "current_assets_amount_original": {"data_type": "decimal"},
    "current_assets_amount_usd": {"data_type": "decimal"},
    "fixed_assets_amount_original": {"data_type": "decimal"},
    "fixed_assets_amount_usd": {"data_type": "decimal"},
    "equity_amount_original": {"data_type": "decimal"},
    "equity_amount_usd": {"data_type": "decimal"},
    "total_debt_amount_original": {"data_type": "decimal"},
    "total_debt_amount_usd": {"data_type": "decimal"},
    "current_liabilities_amount_original": {"data_type": "decimal"},
    "current_liabilities_amount_usd": {"data_type": "decimal"},
    "long_term_liabilities_amount_original": {"data_type": "decimal"},
    "long_term_liabilities_amount_usd": {"data_type": "decimal"},
    "fx_rate_to_usd": {"data_type": "decimal"},
    "fx_rate_date": {"data_type": "date"},
    "fx_source": {"data_type": "text"},
    "source_url": {"data_type": "text"},
    "raw_financial_record": {"data_type": "text"},
}


def copy_dlt_columns(columns: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {name: dict(spec) for name, spec in columns.items()}


COMPANIES_COLUMNS = (
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_line_number",
    "source_record_id",
    "source_payload_hash",
    "org_number",
    "vat_id",
    "legal_name",
    "legal_form_code",
    "legal_form_description_original",
    "legal_form_description_en",
    "registration_date",
    "incorporation_date",
    "website",
    "phone",
    "nace1_code",
    "nace1_description_original",
    "nace1_description_en",
    "nace2_code",
    "nace2_description_original",
    "nace2_description_en",
    "nace3_code",
    "nace3_description_original",
    "nace3_description_en",
    "articles_purpose_original",
    "articles_purpose_en",
    "activity_text_original",
    "activity_text_en",
    "employee_count",
    "has_registered_employee_count",
    "business_address_lines",
    "business_postal_code",
    "business_city",
    "business_municipality",
    "business_municipality_code",
    "business_country_code",
    "is_vat_registered",
    "is_enterprise_register_registered",
    "is_group_member",
    "parent_org_number",
    "last_submitted_accounts_year",
    "status",
    "is_active",
    "source_url",
    "raw_entity",
)

FINANCIAL_STATEMENTS_COLUMNS = (
    "country_iso2",
    "source_slug",
    "source_run_id",
    "source_line_number",
    "source_record_id",
    "source_payload_hash",
    "org_number",
    "legal_name",
    "website",
    "last_submitted_accounts_year",
    "filing_id",
    "journal_number",
    "accounts_type",
    "legal_form_code",
    "is_parent_company",
    "period_start_date",
    "period_end_date",
    "fiscal_year",
    "currency",
    "liquidation_accounts",
    "statement_layout",
    "is_not_audited",
    "opted_out_audit",
    "is_small_enterprise",
    "accounting_rules",
    "operating_revenue_amount_original",
    "operating_revenue_amount_usd",
    "operating_costs_amount_original",
    "operating_costs_amount_usd",
    "operating_result_amount_original",
    "operating_result_amount_usd",
    "net_financial_items_amount_original",
    "net_financial_items_amount_usd",
    "pretax_result_amount_original",
    "pretax_result_amount_usd",
    "net_result_amount_original",
    "net_result_amount_usd",
    "total_assets_amount_original",
    "total_assets_amount_usd",
    "current_assets_amount_original",
    "current_assets_amount_usd",
    "fixed_assets_amount_original",
    "fixed_assets_amount_usd",
    "equity_amount_original",
    "equity_amount_usd",
    "total_debt_amount_original",
    "total_debt_amount_usd",
    "current_liabilities_amount_original",
    "current_liabilities_amount_usd",
    "long_term_liabilities_amount_original",
    "long_term_liabilities_amount_usd",
    "fx_rate_to_usd",
    "fx_rate_date",
    "fx_source",
    "source_url",
    "raw_financial_record",
)

# Big/incompressible provenance columns that stay in DuckDB staging but are not
# exported to ClickHouse: raw_* is the full source JSON (largest column) and
# source_payload_hash is a per-row SHA256 that cannot compress. Nothing queries
# them. See dagster_v3/CLAUDE.md. The full tuples above remain the DuckDB +
# migration/DDL contract; the *_EXPORT_COLUMNS subsets drive the ClickHouse insert.
CLICKHOUSE_EXCLUDED_COLUMNS = frozenset(
    {"raw_entity", "raw_financial_record", "source_payload_hash"}
)


def _export_columns(columns: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(column for column in columns if column not in CLICKHOUSE_EXCLUDED_COLUMNS)


# Free-text _en columns are supplied by the translator service via the
# corpscout.norway_companies_translated view (migration 000058 drops them from the
# base companies table). They are no longer exported from DuckDB. The 4 reference
# _en columns (legal_form/nace) stay — they are populated by reference-data joins.
COMPANIES_TRANSLATED_EN_COLUMNS = frozenset(
    {"articles_purpose_en", "activity_text_en"}
)

COMPANIES_EXPORT_COLUMNS = tuple(
    column
    for column in COMPANIES_COLUMNS
    if column not in (CLICKHOUSE_EXCLUDED_COLUMNS | COMPANIES_TRANSLATED_EN_COLUMNS)
)
FINANCIAL_STATEMENTS_EXPORT_COLUMNS = _export_columns(FINANCIAL_STATEMENTS_COLUMNS)

COMPANIES_DDL = f"""
CREATE TABLE IF NOT EXISTS {QUALIFIED_COMPANIES_TABLE}
(
    country_iso2 LowCardinality(String),
    source_slug LowCardinality(String),
    source_run_id String,
    source_line_number UInt64,
    source_record_id String,
    source_payload_hash FixedString(64),
    org_number String,
    vat_id String,
    legal_name String,
    legal_form_code String,
    legal_form_description_original String,
    legal_form_description_en String,
    registration_date String,
    incorporation_date String,
    website String,
    phone String,
    nace1_code String,
    nace1_description_original String,
    nace1_description_en String,
    nace2_code String,
    nace2_description_original String,
    nace2_description_en String,
    nace3_code String,
    nace3_description_original String,
    nace3_description_en String,
    articles_purpose_original String,
    articles_purpose_en String,
    activity_text_original String,
    activity_text_en String,
    employee_count Nullable(Int64),
    has_registered_employee_count UInt8,
    business_address_lines String,
    business_postal_code String,
    business_city String,
    business_municipality String,
    business_municipality_code String,
    business_country_code String,
    is_vat_registered UInt8,
    is_enterprise_register_registered UInt8,
    is_group_member UInt8,
    parent_org_number String,
    last_submitted_accounts_year String,
    status LowCardinality(String),
    is_active UInt8,
    source_url String,
    raw_entity String
)
ENGINE = ReplacingMergeTree
ORDER BY (org_number)
"""

FINANCIAL_STATEMENTS_DDL = f"""
CREATE TABLE IF NOT EXISTS {QUALIFIED_FINANCIAL_STATEMENTS_TABLE}
(
    country_iso2 LowCardinality(String),
    source_slug LowCardinality(String),
    source_run_id String,
    source_line_number UInt64,
    source_record_id String,
    source_payload_hash FixedString(64),
    org_number String,
    legal_name String,
    website String,
    last_submitted_accounts_year String,
    filing_id Nullable(Int64),
    journal_number String,
    accounts_type LowCardinality(String),
    legal_form_code String,
    is_parent_company UInt8,
    period_start_date Nullable(Date),
    period_end_date Nullable(Date),
    fiscal_year Nullable(Int64),
    currency LowCardinality(String),
    liquidation_accounts UInt8,
    statement_layout String,
    is_not_audited UInt8,
    opted_out_audit UInt8,
    is_small_enterprise UInt8,
    accounting_rules String,
    operating_revenue_amount_original Nullable(Decimal(38, 6)),
    operating_revenue_amount_usd Nullable(Decimal(38, 6)),
    operating_costs_amount_original Nullable(Decimal(38, 6)),
    operating_costs_amount_usd Nullable(Decimal(38, 6)),
    operating_result_amount_original Nullable(Decimal(38, 6)),
    operating_result_amount_usd Nullable(Decimal(38, 6)),
    net_financial_items_amount_original Nullable(Decimal(38, 6)),
    net_financial_items_amount_usd Nullable(Decimal(38, 6)),
    pretax_result_amount_original Nullable(Decimal(38, 6)),
    pretax_result_amount_usd Nullable(Decimal(38, 6)),
    net_result_amount_original Nullable(Decimal(38, 6)),
    net_result_amount_usd Nullable(Decimal(38, 6)),
    total_assets_amount_original Nullable(Decimal(38, 6)),
    total_assets_amount_usd Nullable(Decimal(38, 6)),
    current_assets_amount_original Nullable(Decimal(38, 6)),
    current_assets_amount_usd Nullable(Decimal(38, 6)),
    fixed_assets_amount_original Nullable(Decimal(38, 6)),
    fixed_assets_amount_usd Nullable(Decimal(38, 6)),
    equity_amount_original Nullable(Decimal(38, 6)),
    equity_amount_usd Nullable(Decimal(38, 6)),
    total_debt_amount_original Nullable(Decimal(38, 6)),
    total_debt_amount_usd Nullable(Decimal(38, 6)),
    current_liabilities_amount_original Nullable(Decimal(38, 6)),
    current_liabilities_amount_usd Nullable(Decimal(38, 6)),
    long_term_liabilities_amount_original Nullable(Decimal(38, 6)),
    long_term_liabilities_amount_usd Nullable(Decimal(38, 6)),
    fx_rate_to_usd Nullable(Decimal(38, 12)),
    fx_rate_date Nullable(Date),
    fx_source String,
    source_url String,
    raw_financial_record String
)
ENGINE = ReplacingMergeTree
ORDER BY (org_number, accounts_type, source_record_id)
"""
