---
- name: Deploy cc-dns-worker
  hosts: cc_dns
  become: true
  gather_facts: true
  roles:
    - { role: os_tuning, tags: [os_tuning] }
    - { role: unbound, tags: [unbound] }
    - { role: cc_dns_worker, tags: [cc_dns_worker] }
