\echo bootstrap roles

SELECT format(
  'CREATE ROLE %I LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS PASSWORD %L',
  :'corpscout_user',
  :'corpscout_password'
)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'corpscout_user'
)
\gexec

ALTER ROLE :"corpscout_user"
  WITH LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS;

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L',
  :'temporal_user',
  :'temporal_password'
)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'temporal_user'
)
\gexec

ALTER ROLE :"temporal_user"
  WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD :'temporal_password';
